name: Build (Docker/Windows/MacOS)

on:
  push:
    branches:
      - 'main'
    tags:
      - '*'
  pull_request:
  workflow_dispatch:


jobs:
  
  MacOS:
    runs-on: macos-latest
  
    strategy:
      matrix:
        platform: [x86_64, arm64]
  
    steps:
    
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: main
    
    - name: Install brew packages
      run: |
        brew update
        brew install  gzip xxd
  
    - name: Install vcpkg packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        brew install vcpkg
        vcpkg integrate install
        vcpkg install libpq:${{matrix.platform}}-osx fftw3:${{matrix.platform}}-osx libusb:${{matrix.platform}}-osx pthread:${{matrix.platform}}-osx curl:${{matrix.platform}}-osx soxr:${{matrix.platform}}-osx zeromq:${{matrix.platform}}-osx
  
    - name: Building Libraries and AIS-catcher
      run: |
        # Add your build commands here, replace them with the MacOS equivalent if needed
  
    - name: Prepare output
      run: |
        # Add your output preparation commands here, replace them with the MacOS equivalent if needed 
  
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: "AIS-catcher MacOS ${{matrix.platform}}"
        path: |
          output # or change to the path where your build artifacts are
